[server]
port = 8501
address = "localhost"
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#1f6feb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#313131"
font = "sans serif"

[browser]
gatherUsageStats = false
